import { universeStats } from "../lib/stats.js";
const s = universeStats();
const bar = "=".repeat(60);
console.log(`\n${bar}\nCLAIM — universe findings\n${bar}`);
console.log(`tokens indexed              ${s.tokens}`);
console.log(`generated                   ${s.generatedAt}`);
console.log(`\n--- issuer power ---`);
console.log(`with a permanent delegate   ${s.delegated}`);
console.log(`distinct delegate keys      ${s.delegateKeys}`);
console.log(`largest single-key reach    ${s.largestDelegateReach}`);
console.log(`\n--- balance correctness ---`);
console.log(`multiplier traps            ${s.multiplierTraps}`);
console.log(`worst display               ${s.worstTrapPct?.toFixed(1) ?? "-"}% of real balance`);
console.log(`\n--- exit reality ---`);
console.log(`probed for a route          ${s.probed}`);
console.log(`routable                    ${s.routable}`);
console.log(`no market at all            ${s.probed - s.routable}`);
console.log(`ladders measured            ${s.laddered}`);
console.log(`can shift $10k inside 5%    ${s.canExit10k}`);
console.log(bar);
